### ISSUE TITLE
JNPCT MCH: UAT App

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/jnpct#142]
Before UAT Starts

- [x]  Email client the UAT SOP
- [x]  Email client the Test cases
- [x]  From Client : Get the user list to be created for UAT
- [x]  From Client: Get a confirmation on the organization name
- [x]  From Client: Get dummy or test list of locations and catchment data for UAT
- [x]  Implementation Team: Users, catchments and location upload
- [x]  Implementation Team: Overall testing of the app before giving for UAT
