### ISSUE TITLE
JNPCT MCH: Go Live App

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/jnpct#143]
Functional

- [x] Visit Scheduling Logic: All Forms
- [x] App Flow

Data
- [x]  Void all test data in production
- [x]  Disable UAT users
