### ISSUE TITLE
JNPCT MCH: Checklist: For QA & BA

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/jnpct#145]
- [x] Visit Schedule Logics
- [x]  Over all App flow
- [x]  Disable UAT Users
- [x]  Cross Check User Permissions and User Group
- [x]  Translations - Need to check if done and uploaded by client
